### ISSUE TITLE
Now available on NetBSD

### ISSUE THREAD

**Issue by 0323pin** [KmolYuan/four-bar-rs#3]
FYI, I've packaged and just merged `four-bar` into pkgsrc main branch.
[Commit message for your reference](http://mail-index.netbsd.org/pkgsrc-changes/2023/04/14/msg272461.html) 

Let me know if you would like a PR to add install instructions to the README.md file.

Regards

**Comment by KmolYuan** [comment]
Thanks for the update!
Adding some installation instructions to the README.md file would be helpful for users on this platform. Thanks so much for your hard work and dedication to this project! I'd be more than happy to accept any pull request you create for that purpose.

**Comment by 0323pin** [comment]
Thanks! I'll make a PR in the coming days. Leaving this issue open until then.

**Comment by KmolYuan** [comment]
#4
