### ISSUE TITLE
Tries extracting git hash even from distfile

### ISSUE THREAD

**Issue by 0-wiz-0** [KmolYuan/four-bar-rs#5]
Yesterday I tried fixing the pkgsrc package for four-bar-rs because it was not building. pkgsrc uses the [v7.0.0 tag tarball from github](https://github.com/KmolYuan/four-bar-rs/archive/refs/tags/v7.0.0.tar.gz).
During the build of four-bar-ui, `build.rs` tries to run `git` to find out a revision, which is later used in `four-bar-ui/src/app.rs` via `env!("GIT_HASH")`.
I don't know how this is supposed to work with the distfile, because that does not contain the git metadata files, so even if I provide a git binary during the build, running it will fail.

How is this supposed to work?

The workaround I used in pkgsrc is to delete `four-bar-ui/build.rs` and replace `env!("GIT_HASH")` from the pkgsrc infrastructure.

**Comment by KmolYuan** [comment]
Fixed in 4a4dcfb.

**Comment by 0-wiz-0** [comment]
Confirmed fixed in 7.0.1, thank you!
